website_theme: Cause
website_name: Nodepath
live_domain_url:
website_description_text:
social_media_share_image:
twitter_handle:
icons:
  small_bookmark_icon_image: /images/icons/favicon-16x16.png
  large_bookmark_icon_image: /images/icons/favicon-32x32.png
  small_mobile_icon_image: /images/icons/apple-touch-icon.png
  large_mobile_icon_image: /images/icons/android-chrome-512x512.png
